import Foundation

/// AI-synthesised article fixtures. Every `fact` block references at least one
/// source id; `inference` blocks are labelled and gated; `unknown` blocks state
/// what's missing. This mirrors the Phase 5 citation-gate contract.
enum DemoArticles {

    static let byCaseID: [String: SynthesizedArticle] = {
        var map: [String: SynthesizedArticle] = [:]
        for a in all { map[a.caseID] = a }
        return map
    }()

    static let all: [SynthesizedArticle] = [starlink, northSea, tokyo]

    static let starlink = SynthesizedArticle(
        id: "art_starlink_1", caseID: "case_starlink_atacama", versionNumber: 2,
        headline: "アタカマの『光の列』は、衛星の可視パスで説明できる",
        dek: "複数地点の報告を、公開軌道要素と照合した。",
        blocks: [
            Fx.heading("h1", "何が報告されたか"),
            Fx.fact("b1", "現地時刻21:12前後、アタカマ砂漠周辺の複数の観測者が、等間隔で同一方向へ移動する20個以上の光点を報告した。",
                    claims: ["clm_time", "clm_pattern"], sources: ["s1", "s2"]),
            Fx.heading("h2", "既知現象との照合", gated: true),
            Fx.fact("b2", "観測時刻と方角は、直近の衛星打ち上げ後の可視パスと高い精度で一致した。等間隔・等速で点滅しない挙動は、軌道上に並んだ衛星列の特徴と整合する。",
                    claims: ["clm_pass"], sources: ["s3"], gated: true),
            Fx.inference("b3", "一部報告の『40以上』という数は、列の一部を二重に数えた可能性が高い。",
                         confidence: 0.7, claims: ["clm_count"], gated: true),
            Fx.unknown("b4", "個々の光点の角速度を精密に測定した映像は入手できていない。", missing: ["angular_velocity"], gated: true),
            Fx.heading("h3", "現時点の判断", gated: true),
            Fx.fact("b5", "現在の証拠は衛星の可視パスで十分に説明でき、異常な運動を示す独立した客観データは確認されていない。",
                    claims: ["clm_assessment"], sources: ["s1", "s3"], gated: true),
        ],
        readingMinutes: 3, generatedAt: FixtureClock.day(-1, hour: 14),
        disclosure: .editorReviewed, modelLabel: "synthesis (demo)", promptVersion: "case_synthesis@1.0",
        correctionNote: nil
    )

    static let northSea = SynthesizedArticle(
        id: "art_northsea_1", caseID: "case_north_sea_notable", versionNumber: 3,
        headline: "北海の高速光点：良質な証拠と、残る未解明",
        dek: "3地点の独立報告を統合し、衛星・航空データと照合した。",
        blocks: [
            Fx.heading("h1", "何が報告されたか"),
            Fx.fact("b1", "現地22:10〜22:19、北海沿岸の3つの離れた地点から、通常の航空機より速く見える光点が報告された。うち2件は連続映像を伴う。",
                    claims: ["clm_multi", "clm_video"], sources: ["s1", "s2", "s3"]),
            Fx.heading("h2", "照合の結果", gated: true),
            Fx.fact("b2", "確認できた衛星の可視パスおよび一般の航空情報の範囲では、時刻・運動を十分に説明する候補は見つからなかった。",
                    claims: ["clm_nomatch"], sources: ["s3"], gated: true),
            Fx.inference("b3", "推定高度が報告間で大きく異なることは、視距離の誤差か、複数物体を同一視した可能性を示唆する。",
                         confidence: 0.55, claims: ["clm_altitude"], gated: true),
            Fx.unknown("b4", "3地点の映像の正確な時刻同期と、独立したレーダー記録は確認できていない。",
                       missing: ["time_sync", "radar"], gated: true),
            Fx.heading("h3", "現時点の判断", gated: true),
            Fx.fact("b5", "複数の独立地点と映像という比較的良質な証拠がある一方、既知現象では現時点で十分に説明できない。未解明部分が残るが、これは地球外起源を意味しない。",
                    claims: ["clm_assessment"], sources: ["s1", "s2", "s3"], gated: true),
        ],
        readingMinutes: 4, generatedAt: FixtureClock.day(0, hour: 15),
        disclosure: .autoGenerated, modelLabel: "synthesis (demo)", promptVersion: "case_synthesis@1.0",
        correctionNote: "独立報告数を2から3へ更新（映像追加）。"
    )

    static let tokyo = SynthesizedArticle(
        id: "art_tokyo_1", caseID: "case_tokyo_bay_lights", versionNumber: 1,
        headline: "東京湾の『止まる光』：航空機の可能性が高い",
        dek: "湾岸の複数報告を、時刻と灯火配置から検討した。",
        blocks: [
            Fx.heading("h1", "何が報告されたか"),
            Fx.fact("b1", "現地19:48〜20:05、東京湾岸の複数地点から、三角形に配置された3つの灯火が報告された。",
                    claims: ["clm_config"], sources: ["s1", "s2"]),
            Fx.heading("h2", "検討", gated: true),
            Fx.fact("b2", "時刻は主要空港の進入時間帯と一致し、灯火の配置は着陸灯・翼端灯と整合する。",
                    claims: ["clm_approach"], sources: ["s1"], gated: true),
            Fx.inference("b3", "『完全に停止していた』という印象は、観測者へほぼ正対して進入する航空機で生じやすい視線方向の錯覚で説明できる。",
                         confidence: 0.6, claims: ["clm_illusion"], gated: true),
            Fx.unknown("b4", "灯火の角速度を測る固定カメラ映像と、同時刻の航空交通の独立記録は不足している。",
                       missing: ["angular_velocity", "traffic_log"], gated: true),
        ],
        readingMinutes: 2, generatedAt: FixtureClock.day(0, hour: 22, minute: 40),
        disclosure: .autoGenerated, modelLabel: "synthesis (demo)", promptVersion: "case_synthesis@1.0",
        correctionNote: nil
    )
}
