import Foundation

/// The editorial status of a `UAPCase`.
///
/// These values intentionally avoid a true/false framing. "Unresolved" never
/// means "extraterrestrial"; "explained" never means "not worth reading".
enum CaseStatus: String, Codable, Sendable, CaseIterable, Identifiable {
    case explained
    case likelyExplained = "likely_explained"
    case insufficientData = "insufficient_data"
    case underReview = "under_review"
    case notableUnresolved = "notable_unresolved"
    case disputed
    case withdrawn

    var id: String { rawValue }

    /// Localization key for the user-facing label. Never render the raw case name.
    var labelKey: String { "case.status.\(rawValue)" }

    /// SF Symbol paired with the label so status never relies on colour alone.
    var systemImage: String {
        switch self {
        case .explained: "checkmark.seal"
        case .likelyExplained: "checkmark.circle"
        case .insufficientData: "questionmark.circle"
        case .underReview: "scope"
        case .notableUnresolved: "sparkle.magnifyingglass"
        case .disputed: "exclamationmark.triangle"
        case .withdrawn: "arrow.uturn.backward.circle"
        }
    }

    /// Semantic signal role used by the design system to pick a token.
    var signal: SignalRole {
        switch self {
        case .explained, .likelyExplained: .green
        case .insufficientData: .amber
        case .underReview: .cyan
        case .notableUnresolved: .violet
        case .disputed, .withdrawn: .red
        }
    }
}

/// How precisely a case location may be shown on the map.
enum LocationPrecision: String, Codable, Sendable {
    case exact
    case approximate
    case regionOnly = "region_only"
    case withheld

    var labelKey: String { "location.precision.\(rawValue)" }

    /// Radius, in metres, used to render an uncertainty ring. `nil` == a point.
    var uncertaintyRadiusMeters: Double? {
        switch self {
        case .exact: nil
        case .approximate: 8_000
        case .regionOnly: 60_000
        case .withheld: nil
        }
    }
}

/// Design-system colour role. Views map this to a `SkyColor` token; models stay
/// free of any concrete colour value.
enum SignalRole: String, Codable, Sendable {
    case cyan, violet, amber, green, red, neutral
}

/// Role a source plays relative to a claim or case.
enum EvidenceRole: String, Codable, Sendable {
    case supports
    case contradicts
    case contextualizes

    var labelKey: String { "evidence.role.\(rawValue)" }
}

/// Classifies a source document by origin type.
enum SourceType: String, Codable, Sendable {
    case official
    case press
    case scientific
    case database
    case social
    case openData = "open_data"

    var labelKey: String { "source.type.\(rawValue)" }
    var systemImage: String {
        switch self {
        case .official: "building.columns"
        case .press: "newspaper"
        case .scientific: "atom"
        case .database: "cylinder.split.1x2"
        case .social: "bubble.left.and.bubble.right"
        case .openData: "square.grid.3x3"
        }
    }
}

/// AI generation / human-review disclosure state for an article or briefing.
enum AIDisclosure: String, Codable, Sendable {
    case autoGenerated = "ai_auto"
    case editorReviewed = "ai_reviewed"
    case humanWritten = "human"

    var labelKey: String { "ai.disclosure.\(rawValue)" }
    var systemImage: String {
        switch self {
        case .autoGenerated: "sparkles"
        case .editorReviewed: "checkmark.sparkles"
        case .humanWritten: "person.fill"
        }
    }
}

/// Category of a known-phenomenon explanation candidate.
enum ExplanationCategory: String, Codable, Sendable {
    case satellite, aircraft, fireball, astronomical, weather
    case rocket, drone, cameraArtifact = "camera_artifact", searchlight, other

    var labelKey: String { "explanation.category.\(rawValue)" }
    var systemImage: String {
        switch self {
        case .satellite: "sparkles.tv"
        case .aircraft: "airplane"
        case .fireball: "flame"
        case .astronomical: "moon.stars"
        case .weather: "cloud.bolt"
        case .rocket: "flame.circle"
        case .drone: "sensor.tag.radiowaves.forward"
        case .cameraArtifact: "camera.aperture"
        case .searchlight: "flashlight.on.fill"
        case .other: "questionmark.diamond"
        }
    }
}
