#!/usr/bin/env python3
"""Static App Store release-readiness audit for SkyTrace.

Normal CI runs this in report mode so manual blockers remain visible without
blocking development. Release tags and the manual strict workflow run with
--strict and fail until every credential/configuration/production-data gate is
resolved. This prevents a green unit-test run from being mistaken for a
submission-ready build.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent


@dataclass(frozen=True)
class Check:
    key: str
    title: str
    passed: bool
    detail: str
    owner: str  # automatic | manual | external


def read(path: str) -> str:
    p = ROOT / path
    return p.read_text(encoding="utf-8") if p.exists() else ""


def absent(path: str, needle: str, *, key: str, title: str,
           owner: str, detail: str) -> Check:
    text = read(path)
    return Check(key, title, bool(text) and needle not in text, detail, owner)


def present(path: str, needle: str, *, key: str, title: str,
            owner: str, detail: str) -> Check:
    text = read(path)
    return Check(key, title, needle in text, detail, owner)


def collect() -> list[Check]:
    checks = [
        absent(
            "apps/ios/project.yml", "com.example.skytrace",
            key="bundle-id", title="Real Bundle ID configured", owner="manual",
            detail="Replace com.example.skytrace in XcodeGen/project generation and App Store Connect.",
        ),
        absent(
            "apps/ios/SkyTrace/Services/FakeSubscriptionProvider.swift",
            "com.example.skytrace.plus.monthly",
            key="product-ids", title="Real subscription product IDs configured", owner="manual",
            detail="Monthly/yearly IDs must exactly match App Store Connect.",
        ),
        absent(
            "apps/ios/project.yml", 'DEVELOPMENT_TEAM: ""',
            key="team-id", title="Apple Development Team configured", owner="manual",
            detail="Set the team in Xcode/project settings before Archive.",
        ),
        absent(
            "docs/site/support/index.html", "support@skytrace.app",
            key="support-email", title="Reachable support email configured", owner="manual",
            detail="Replace the placeholder with an address that is actively monitored.",
        ),
        absent(
            "apps/ios/SkyTrace/App/AppEnvironment.swift",
            "production_data_source_not_configured",
            key="production-data", title="Production data repositories connected", owner="external",
            detail="Release remains intentionally blocked until live, approved-source repositories replace the unconfigured seam.",
        ),
        present(
            "apps/ios/SkyTrace/App/SkyTraceApp.swift",
            "let source: DataSourceMode = .localAPI",
            key="fixture-isolation", title="Release does not default to fixtures", owner="automatic",
            detail="The non-Debug app must select the production data seam.",
        ),
        present(
            "apps/ios/SkyTrace/App/AppEnvironment.swift",
            "must never silently fall back to demo cases",
            key="no-silent-fallback", title="Production failure cannot silently show demos", owner="automatic",
            detail="An unavailable production source must fail visibly rather than return fixture news.",
        ),
        present(
            "apps/ios/SkyTrace/Utilities/FeatureFlags.swift",
            "var notificationsEnabled = false",
            key="notification-truthfulness", title="Unimplemented notifications hidden", owner="automatic",
            detail="Notification preferences stay hidden until delivery exists end-to-end.",
        ),
        absent(
            "apps/ios/project.yml", "buildPhase: resources",
            key="storekit-bundle", title="Local StoreKit config excluded from app resources", owner="automatic",
            detail="The .storekit file belongs to the development Run scheme, not the Release bundle.",
        ),
        present(
            "apps/ios/SkyTrace/Resources/PrivacyInfo.xcprivacy",
            "NSPrivacyAccessedAPICategoryUserDefaults",
            key="privacy-manifest", title="Privacy manifest declares UserDefaults access", owner="automatic",
            detail="Re-audit whenever networking, analytics, accounts, or push tokens are added.",
        ),
    ]
    return checks


def markdown(checks: list[Check]) -> str:
    lines = [
        "# SkyTrace Release Readiness",
        "",
        "Generated by `scripts/release_readiness.py`.",
        "",
        "| Status | Gate | Owner | Detail |",
        "|---|---|---|---|",
    ]
    for c in checks:
        icon = "✅" if c.passed else "⛔"
        lines.append(f"| {icon} | {c.title} | {c.owner} | {c.detail} |")
    failed = [c for c in checks if not c.passed]
    lines += ["", f"**Result: {'GO' if not failed else 'NO-GO'} — {len(failed)} blocker(s).**", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true",
                        help="exit non-zero when any gate fails")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--report", type=Path,
                        help="write a Markdown report to this path")
    args = parser.parse_args()

    checks = collect()
    output = json.dumps([asdict(c) for c in checks], ensure_ascii=False, indent=2) \
        if args.json else markdown(checks)
    print(output)

    if args.report:
        report = args.report if args.report.is_absolute() else ROOT / args.report
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(markdown(checks), encoding="utf-8")

    return 1 if args.strict and any(not c.passed for c in checks) else 0


if __name__ == "__main__":
    sys.exit(main())
